apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-hello
  labels:
    app: k8s-web-hello
spec:
  replicas: 10
  selector:
    matchLabels:
      app: k8s-web-hello
  template:
    metadata:
      name: k8s-web-hello
      labels:
        app: k8s-web-hello
    spec:
      containers:
        - name: k8s-web-hello
          image: artemnizhnyk/k8s-web-hello-com
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      restartPolicy: Always
      