apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-to-nginx
  labels:
    app: k8s-web-to-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-web-to-nginx
  template:
    metadata:
      name: k8s-web-to-nginx
      labels:
        app: k8s-web-to-nginx
    spec:
      containers:
        - name: k8s-web-to-nginx
          image: artemnizhnyk/k8s-web-to-nginx-com
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-web-to-nginx
spec:
  selector:
    app: k8s-web-to-nginx
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3000
  type: LoadBalancer